version: "3.6"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "65432:5432"
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    env_file:
      - ./hasura/.env.local
  auth-server:
    image: auth-server:latest
    ports:
      - "9090:9090"
    depends_on:
      - "graphql-engine"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=local
